/* @Authur:	Dean Beckford
   @Date:	Jan-15, 2018
   create_database.sql
   
   This script create all tables along with necessary constraints for database.
  */

/* Turn of FOREIGN KEY CONSTRAINT Check*/
SET FOREIGN_KEY_CHECKS=0;

/* Drop all exiting tables*/
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS SPONSOR;
DROP TABLE IF EXISTS SCHOOL;
DROP TABLE IF EXISTS JOB_OFFER;
DROP TABLE IF EXISTS EMPLOYER;
DROP TABLE IF EXISTS EMPLOYER_JOB;
DROP TABLE IF EXISTS JOB_ASSIGNMENT;
DROP TABLE IF EXISTS JOB;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FACILITATOR;


/* Create STUDENT table*/
CREATE TABLE STUDENT(
	StudId		INTEGER		AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Fname 		VARCHAR(25)	NOT NULL,
	Mname 		VARCHAR(25),
	Lname 		VARCHAR(25)	NOT NULL,
	Gender 		VARCHAR(1)	NOT NULL,
	StudAddress	VARCHAR(75) NOT NULL,
	Dob   		DATE	NOT NULL,
	Phone 	 	VARCHAR(12),
	Gpa FLOAT(5,2) 	DEFAULT 2.00	NOT NULL,
	Email  		VARCHAR(30)	NOT NULL,
	SchoolId 	INTEGER 	NOT NULL,
	SponsorId 	INTEGER,
	JobId 		INTEGER,
	UserId		INTEGER		NOT NULL,
	FOREIGN KEY (SchoolId) 	REFERENCES 	SCHOOL(SchId)  	ON DELETE CASCADE,
	FOREIGN KEY (SponsorId) REFERENCES 	SPONSOR(SpnId) 	ON DELETE CASCADE,
	FOREIGN KEY (JobId) 	REFERENCES 	JOB(JobId)  	ON DELETE CASCADE,
	FOREIGN KEY (UserId) 	REFERENCES 	USERS(UserId)  	ON DELETE CASCADE
);

CREATE TABLE SPONSOR(
	SpnId 		INTEGER		AUTO_INCREMENT	 NOT NULL 	PRIMARY KEY,
	UserId		INTEGER		NOT NULL,
	SpnName		VARCHAR(50)	NOT NULL,
	SpnAddress 	VARCHAR(75) NOT NULL,
	Phone  		VARCHAR(12)	NOT NULL,
	Email  		VARCHAR(30)	NOT NULL,
	FOREIGN KEY (UserId) 	REFERENCES 	USERS(UserId)  	ON DELETE CASCADE
);


CREATE TABLE SCHOOL(
	SchId 		INTEGER		AUTO_INCREMENT	 NOT NULL	PRIMARY KEY,
	SchName		VARCHAR(30)	NOT NULL,
	SchAddress 	VARCHAR(75) NOT NULL,
	Phone  		VARCHAR(12)	NOT NULL,
	Email  		VARCHAR(30)	NOT NULL,
	Rep			VARCHAR(30)
);

CREATE TABLE EMPLOYER(
	EmpId 		INTEGER		AUTO_INCREMENT	NOT NULL 	PRIMARY KEY,
	UserId		INTEGER		NOT NULL,
	EmpName		VARCHAR(30)	NOT NULL,
	EmpAddress 	VARCHAR(75) NOT NULL,
	Phone  		VARCHAR(10)	NOT NULL,
	Email  		VARCHAR(30)	NOT NULL,
	Rep			VARCHAR(30),
	FOREIGN KEY (UserId) 	REFERENCES 	USERS(UserId)  	ON DELETE CASCADE
);

CREATE TABLE FACILITATOR(
	FId		INTEGER	AUTO_INCREMENT	NOT NULL 	PRIMARY KEY,
	UserId	INTEGER		NOT NULL,
	Fname	VARCHAR(25) NOT NULL,
	Mname	VARCHAR(25),
	Lname	VARCHAR(25) NOT NULL,
	Email  		VARCHAR(30)	NOT NULL,
	Phone  		VARCHAR(10)	NOT NULL,
	FOREIGN KEY (UserId) 	REFERENCES 	USERS(UserId)  	ON DELETE CASCADE
);

CREATE TABLE JOB(
	JobId 		INTEGER		AUTO_INCREMENT	 NOT NULL 	PRIMARY KEY,
	EmpId 		INTEGER		NOT NULL,
	JobTitle	VARCHAR(30)	NOT NULL,
	JobDescr 	VARCHAR(350) NOT NULL,
	Location	VARCHAR(250) NOT NULL,
	PayRate		FLOAT(5,2) 	DEFAULT 0.00 NOT NULL,
	FOREIGN KEY (EmpId)	REFERENCES	EMPLOYER(EmpId) ON DELETE CASCADE
);
	

CREATE TABLE USERS(
	UserId		INTEGER		AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	UserName 	VARCHAR(30)	NOT NULL UNIQUE,
	Password	VARCHAR(30)	NOT NULL,
	Role 		INTEGER  	DEFAULT 0 NOT NULL,
	Status		BOOLEAN		DEFAULT FALSE
);

SET FOREIGN_KEY_CHECKS=1;